apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
        - name: apisix
          image: apache/apisix:latest
          ports:
            - containerPort: 9080
            - containerPort: 9443
          volumeMounts:
            - name: apisix-config-volume
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
      volumes:
        - name: apisix-config-volume
          configMap:
            name: apisix-config