apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.4.15
          command:
            - /usr/local/bin/etcd
          args:
            - --data-dir=/etcd-data
            - --name=etcd
            - --advertise-client-urls=http://$(POD_IP):2379
            - --listen-client-urls=http://0.0.0.0:2379
            - --initial-advertise-peer-urls=http://$(POD_IP):2380
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-cluster=etcd=http://$(POD_IP):2380
            - --initial-cluster-token=etcd-cluster-1
            - --initial-cluster-state=new
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - mountPath: /etcd-data
              name: etcd-data
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: etcd-pvc
