apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jaeger
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686
            - containerPort: 6831
              protocol: UDP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
            - name: MEMORY_MAX_TRACES
              value: "100000"
          readinessProbe:
            httpGet:
              path: "/"
              port: 14269
          livenessProbe:
            httpGet:
              path: "/"
              port: 14269
