apiVersion: v1
kind: Service
metadata:
  namespace: jaeger
  name: jaeger-query-ui
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 16686
      protocol: TCP
      name: query-http
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  namespace: jaeger
  name: jaeger-query
  labels:
    app: jaeger
spec:
  ports:
    - port: 80
      targetPort: 16686
      protocol: TCP
      name: query-http
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  namespace: jaeger
  name: jaeger-traces
  labels:
    app: jaeger
spec:
  ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
  selector:
    app: jaeger
