apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:latest
          env:
            - name: LDAP_ORGANISATION
              value: "MyOrg"
            - name: LDAP_DOMAIN
              value: "proconion.com"
            - name: LDAP_ADMIN_PASSWORD
              value: "adminpassword"
            - name: LDAP_BASE_DN
              value: "dc=proconion,dc=com"
          ports:
            - containerPort: 389
          volumeMounts:
            - mountPath: /var/lib/ldap
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openldap-pvc
