apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: kong
spec:
  template:
    spec:
      containers:
        - name: kong-migrations
          image: kong:latest
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "postgres.kong.svc.cluster.local"
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: password
          command: ["kong", "migrations", "bootstrap"]
      restartPolicy: OnFailure
