apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  ports:
    - name: http
      port: 8000
    - name: https
      port: 8443
  selector:
    app: kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: kong
spec:
  ports:
    - name: admin-http
      port: 8001
    - name: admin-https
      port: 8444
  selector:
    app: kong
