apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:latest
          ports:
            - containerPort: 8080  # Port for accessing the KrakenD API Gateway
      volumes:
        - name: config-volume
          configMap:
            name: krakend-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend
data:
  krakend-config.yaml: |
    version: 2
    timeout: 3000ms
    endpoints:
    - endpoint: /service1
      method: GET
      extra_config:
        github_com/devopsfaith/krakend-gologging/logging:
          level: DEBUG
      backend:
      - url_pattern: /filename1.txt
        host: nginx.nginx.svc.cluster.local
        encoding: json
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-service
  namespace: krakend
spec:
  selector:
    app: krakend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP