apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-api-gateway
  namespace: kong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong-api-gateway
  template:
    metadata:
      labels:
        app: kong-api-gateway
    spec:
      containers:
        - name: kong
          image: kong:latest # You might want to pin to a specific version
          env:
            - name: KONG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: database
            - name: KONG_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_host
            - name: KONG_PG_USER
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_user
            - name: KONG_PG_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_password
            - name: KONG_PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_database
          # Add other environment variables and configurations if necessary
          ports:
            - name: admin
              containerPort: 8001
            - name: proxy
              containerPort: 8000
            - name: admin-gui
              containerPort: 8002
      # Add readiness and liveness probes if necessary
