apiVersion: v1
kind: Service
metadata:
  name: kong-api-gateway-proxy
  namespace: kong
spec:
  type: NodePort # Using LoadBalancer for external access, modify as per requirements
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
  selector:
    app: kong-api-gateway

---
apiVersion: v1
kind: Service
metadata:
  name: kong-api-gateway-admin
  namespace: kong
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 8001
      targetPort: 8001
  selector:
    app: kong-api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-gui
  namespace: kong
spec:
  type: ClusterIP # Or LoadBalancer if you're using a cloud provider
  ports:
    - name: admin-gui
      port: 8002
      targetPort: 8002
  selector:
    app: kong-api-gateway
