apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: kong
spec:
  template:
    spec:
      containers:
        - name: kong-migrations
          image: kong:latest
          env:
            - name: KONG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: database
            - name: KONG_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_host
            - name: KONG_PG_USER
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_user
            - name: KONG_PG_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_password
            - name: KONG_PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: pg_database
          command: ["kong", "migrations", "bootstrap"]
      restartPolicy: OnFailure
