apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  namespace: krakend
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "version": 3,
      "name": "My API GW",
      "port": 8080,
      "cache_ttl": "3600s",
      "timeout": "3s",
      "extra_config": {
        "telemetry/logging": {
          "level":  "DEBUG",
          "prefix": "[KRAKEND]",
          "syslog": false,
          "stdout": true
        },
        "telemetry/metrics": {
          "collection_time": "60s",
          "proxy_disabled": false,
          "router_disabled": false,
          "backend_disabled": false,
          "endpoint_disabled": false,
          "listen_address": ":8090"
        },
        "security/cors": {}
      },
      "endpoints": [
        {
          "endpoint": "/product1",
          "method": "GET",
          "output_encoding": "no-op",
          "extra_config": {},
          "backend": [
            {
              "url_pattern": "/product1",
              "encoding": "no-op",
              "sd": "static",
              "method": "GET",
              "extra_config": {},
              "host": [
                "http://nginx-service.nginx.svc.cluster.local"
              ],
              "disable_host_sanitize": true
            }
          ]
        },
        {
          "endpoint": "/product2",
          "method": "GET",
          "output_encoding": "no-op",
          "extra_config": {},
          "backend": [
            {
              "url_pattern": "/product2",
              "encoding": "no-op",
              "sd": "static",
              "method": "GET",
              "extra_config": {},
              "host": [
                "http://nginx-service.nginx.svc.cluster.local"
              ],
              "disable_host_sanitize": true
            }
          ]
        }
      ]
    }