apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  namespace: krakend
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "version": 3,
      "name": "My Gateway",
      "port": 8080,
      "cache_ttl": "3600s",
      "timeout": "3s",
      "plugin": {
        "pattern": ".so",
        "folder": "./plugins/server-plugin/krakend-server-ldap/"
      },
      "extra_config": {
        "telemetry/logging": {
          "level":  "DEBUG",
          "prefix": "[KRAKEND]",
          "syslog": false,
          "stdout": true
        },
        "telemetry/metrics": {
          "collection_time": "60s",
          "proxy_disabled": false,
          "router_disabled": false,
          "backend_disabled": false,
          "endpoint_disabled": false,
          "listen_address": ":8090"
        },
        "security/cors": {
          "allow_origins": ["*"],
          "allow_methods": [ "POST", "GET" ],
          "allow_headers": [ "Origin", "Authorization", "Content-Type" ],
          "expose_headers": [ "Content-Length" ],
          "max_age": "12h"
        },
        "plugin/http-server": {
          "name": ["krakend-server-ldap"],
          "krakend-server-ldap": {
            "ldap_uri": "openldap-service.ldap.svc.cluster.local:389",
            "base_dn": "ou=users,dc=proconion,dc=com"
          }
        },
        "proxy": {
          "sequential": true
        }
      },
      "endpoints": [
        {
          "endpoint": "/secure",
          "extra_config": {
            
          },
          "backend": [
            {
              "url_pattern": "/nginx-service-product1/",
              "extra_config": {
              },
              "host": [
                "http://nginx-service-product1.nginx.svc.cluster.local"
              ]
            }
          ]
        }
      ]
    }
