apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
  namespace: krakend
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          #image: m6f13/krakend:2.4.2
          image: devopsfaith/krakend:watch
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          command: [ "/usr/bin/krakend" ]
          #args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
          args: [ "run", "-d", "-c", "/etc/config/krakend/krakend.json", "-p", "8080" ]
          env:
            - name: KRAKEND_PORT
              value: "8080"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/krakend
      volumes:
        - name: config-volume
          configMap:
            name: krakend-cm
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  runAsNonRoot: true
          #  runAsUser: 1000
          #  readOnlyRootFilesystem: true
          #  capabilities:
          #    drop:
          #      - ALL
          #    add:
          #      - NET_BIND_SERVICE
          #env:
          #  - name: KRAKEND_PORT
          #    value: "8080"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0