apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  namespace: krakend
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "version": 3,
      "name": "My Gateway",
      "port": 8080,
      "cache_ttl": "3600s",
      "timeout": "3s",
      "plugin": {
        "pattern": ".so",
        "folder": "./plugins/server-plugin/krakend-server-ldap/"
      },
      "extra_config": {
        "telemetry/logging": {
          "level":  "DEBUG",
          "prefix": "[KRAKEND]",
          "syslog": false,
          "stdout": true
        },
        "telemetry/metrics": {
          "collection_time": "60s",
          "proxy_disabled": false,
          "router_disabled": false,
          "backend_disabled": false,
          "endpoint_disabled": false,
          "listen_address": ":8090"
        },
        "security/cors": {
          "allow_origins": ["*"],
          "allow_methods": [ "POST", "GET" ],
          "allow_headers": [ "Origin", "Authorization", "Content-Type" ],
          "expose_headers": [ "Content-Length" ],
          "max_age": "12h"
        },
        "plugin/http-server": {
          "name": ["krakend-server-ldap"],
          "krakend-server-ldap": {
            "ldap_uri": "openldap-service.ldap.svc.cluster.local:389",
            "base_dn": "ou=users,dc=proconion,dc=com"
          }
        },
        "telemetry/opencensus": {
          "sample_rate": 100,
          "reporting_period": 1,
          "enabled_layers": {
            "backend": true,
            "router": true
          },
          "exporters": {
            "jaeger": {
              "endpoint": "http://jaeger-traces.jaeger.svc.cluster.local:14268/api/traces",
              "service_name": "krakend"
            }
          }
        }
      },
      "endpoints": [
        {
          "@comment": "Feature: Mocked response",
          "endpoint": "/mocked-response",
          "method": "GET",
          "output_encoding": "json",
          "backend": [{"host": ["http://unexistent_backend"], "url_pattern": "/"}],
          "extra_config": {
            "proxy": {
              "static": {
                "data": {
                  "an_integer": 123,
                  "an_array": [
                    "arr1",
                    "arr2"
                  ],
                  "an_object": {
                    "obj": "obj1"
                  }
                },
                "strategy": "always"
              }
            }
          }
        },
        {
          "endpoint": "/secure",
          "backend": [
            {
              "host": ["https://api.github.com"],
              "url_pattern": "/users/m6f13",
              "allow": [
                "avatar_url",
                "name",
                "company",
                "blog",
                "location",
                "mail",
                "hireable",
                "public_repos"
              ],
              "mapping": {
                "blog": "website"
              },
              "group": "github_response"
            },
            {
              "url_pattern": "/nginx-service-product1/",
              "extra_config": {
              },
              "host": [
                "http://nginx-service-product1.nginx.svc.cluster.local"
              ]
            }
          ],
          "extra_config": {
            "proxy": {
              "sequential": true
            }
          }
        },
        {
          "@comment": "Feature: Aggregation + Basic transformation (filtering & mapping) + grouping",
          "endpoint": "/git/{user}",
          "backend": [
            {
              "host": ["https://api.github.com"],
              "url_pattern": "/users/{user}",
              "allow": [
                "avatar_url",
                "name",
                "company",
                "blog",
                "location",
                "mail",
                "hireable",
                "followers",
                "public_repos",
                "public_gists"
              ],
              "mapping": {
                "blog": "website"
              },
              "group": "user"
            },
            {
              "host": ["https://api.github.com"],
              "url_pattern": "/users/{user}/repos",
              "mapping": {
                "collection": "repos"
              },
              "is_collection": true
            }
          ]
        },
        {
          "@comment": "Feature: Aggregation + backend rate limiting + endpoint rate limiting",
          "endpoint": "/shop",
          "backend": [
            {
              "url_pattern": "/shop/campaigns.json",
              "allow": [ "campaigns" ]
            },
            {
              "url_pattern": "/shop/products.json",
              "allow": [ "products" ],
              "extra_config": {
                "qos/ratelimit/proxy": {
                  "max_rate": 1,
                  "capacity": 1
                }
              }
            }
          ],
          "extra_config": {
            "qos/ratelimit/router": {
              "max_rate": 2
            }
          }
        }
      ]
    }
