apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  namespace: krakend
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "version": 3,
      "name": "My API GW",
      "port": 8080,
      "endpoints": [
        {
          "endpoint": "/nginx-service-product1/product.txt",
          "method": "GET",
          "output_encoding": "json",
          "headers_to_pass": ["Authorization"],
          "backend": [
            {
              "host": ["http://ldap-middleware.middleware.svc.cluster.local:5000"],
              "url_pattern": "/authenticate",
              "encoding": "json",
              "sd": "static",
              "extra_config": {}
            },
            {
              "host": ["http://nginx-service-product1.nginx.svc.cluster.local"],
              "url_pattern": "/nginx-service-product1/product.txt",
              "extra_config": {
                "github.com/devopsfaith/krakend-jose/validator": {
                  "alg": "",
                  "jwk-url": "http://middleware-service.middleware.svc.cluster.local:5000/auth",
                  "disable_jwk_security": true
                }
              }
            }
          ]
        }
      ]
    }

