apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  namespace: krakend
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "version": 3,
      "name": "My API GW",
      "port": 8080,
      "endpoints": [
        {
          "endpoint": "/test",
          "method": "GET",
          "output_encoding": "json",
          "backend": [
            {
              "host": [
                "http://127.0.0.1:8080"
              ],
              "url_pattern": "/static-response",
              "disable_host_sanitize": true,
              "encoding": "no-op",
              "extra_config": {
                "github.com/devopsfaith/krakend/proxy": {
                  "static": {
                    "data": {
                      "message": "Authentication Successful!"
                    }
                  }
                }
              }
            }
          ]
        }
      ],
      "extra_config": {
        "github.com/devopsfaith/krakend-martian": {
          "fifo.Group": {
            "scope": ["request"],
            "aggregateErrors": false,
            "modifiers": [
              {
                "mod.Auth": {
                  "type": "Basic",
                  "strategy": "ldap",
                  "options": {
                    "ldap": {
                      "host": "openldap-service.ldap.svc.cluster.local:389",
                      "baseDN": "dc=proconion,dc=com",
                      "useSSL": false,
                      "startTLS": false
                    }
                  }
                }
              }
            ]
          }
        }
      }
    }

